name: Terraform CI/CD
on:
  push:
    branches:
      - main
env:
  tf_version: 'latest'
  tg_version: 'latest'
  working_dir: './multi-lxc'

jobs:
  checks:
    runs-on: "self-hosted"  
    #container:
     # image: ubuntu:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      # - name: Check terragrunt HCL
      #   uses: gruntwork-io/terragrunt-action@v2
      #   with:
      #     tf_version: ${{ env.tf_version }}
      #     tg_version: ${{ env.tg_version }}
      #     tg_dir: ${{ env.working_dir }}
      #     tg_command: 'hclfmt --terragrunt-check --terragrunt-diff'

      - name: Install 1Password CLI    
        uses: 1password/install-cli-action@v1

      - name: Configure 1Password CLI  
        uses: 1password/load-secrets-action/configure@v1
        with:
          #service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          connect-host: ${{ secrets.OP_CONNECT_HOST }}
          connect-token: ${{ secrets.OP_CONNECT_TOKEN }}

      - name: Load Terraform Credentials
        id: load-terraform-credentials
        uses: 1password/load-secrets-action@v1
        with:
            export-env: True
        env:
            TF_VAR_ssh_password: op://secrets/Terraform/ssh_password
            TF_VAR_ssh_user: op://secrets/Terraform/ssh_user
            TF_VAR_ciuser: op://secrets/Terraform/ciuser
            TF_VAR_cipassword: op://secrets/Terraform/cipassword
            TF_VAR_ssh_pub_key: op://secrets/Terraform/ssh_pub_key
            TF_VAR_proxmox_api_token_id: op://secrets/ProxmoxAPI/username
            TF_VAR_proxmox_api_token_secret: op://secrets/ProxmoxAPI/password
            TF_VAR_proxmox_api_url: op://secrets/Terraform/host
            TF_VAR_AWS_ACCESS_KEY_ID: op://secrets/Terraform/minio_access_key
            TF_VAR_AWS_SECRET_ACCESS_KEY: op://secrets/Terraform/minio_secret_key
            TF_VAR_AWS_ENDPOINT_URL_S3: op://secrets/Terraform/minio_endpoint

  plan:
      runs-on: self-hosted
      needs: [ checks ]
      steps:
      - name: 'Checkout'
        uses: actions/checkout@main
          
      - name: Plan
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'plan'
          
  deploy:
      runs-on: self-hosted
      needs: [ plan ]
      if: github.ref == 'refs/heads/main'
      steps:
        - name: 'Checkout'
          uses: actions/checkout@main
          
        - name: Deploy
          uses: gruntwork-io/terragrunt-action@v2
          with:
            tf_version: ${{ env.tf_version }}
            tg_version: ${{ env.tg_version }}
            tg_dir: ${{ env.working_dir }}
            tg_command: 'apply'