name: Terraform CI/CD
on:
  push:
    branches:
      - main
env:
    working-directory: './multi-lxc'
    ssh_password: op://secrets/Terraform/ssh_password
    ssh_user: op://secrets/Terraform/ssh_user
    ciuser: op://secrets/Terraform/ciuser
    cipassword: op://secrets/Terraform/cipassword
    ssh_pub_key: op://secrets/Terraform/ssh_pub_key
    proxmox_api_token_id: op://secrets/ProxmoxAPI/username
    proxmox_api_token_secret: op://secrets/ProxmoxAPI/password
    proxmox_api_url: op://secrets/Terraform/host
    minio_access_key: op://secrets/Terraform/minio_access_key
    minio_secret_key: op://secrets/Terraform/minio_secret_key
    minio_endpoint: op://secrets/Terraform/minio_endpoint

jobs:
  deploy:
    runs-on: "self-hosted"  # (optional) name of the runner labels, groups
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
      - uses: 1password/install-cli-action@v1
      - uses: 1password/load-secrets-action/configure@v1
        with:
        export-env: True
        #service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          connect-host: ${{ secrets.OP_CONNECT_HOST }}
          connect-token: ${{ secrets.OP_CONNECT_TOKEN }}

      - name: Load Terraform Credentials
        id: load-terraform-credentials
        uses: 1password/load-secrets-action@v1
        with:
            export-env: True
    

      - name: 'Terragrunt Init'
        id: init
        run: terraform init
              
      - name: 'Terragrunt Plan'
        id: plan
        run: terraform plan       

      - name: 'Terragrunt Apply'
        id: apply
        run: terraform apply -auto-approve     
       

      

