name: Terraform CI/CD
on:
  push:
    branches:
      - main
   
jobs:
  deploy:
    runs-on: "self-hosted"  
    defaults:
      run:
        working-directory: './multi-lxc'
    env: 
      TF_VAR_ssh_password: ${{ env.ssh_password }}
      TF_VAR_ssh_user: ${{ env.ssh_user }}
      TF_VAR_ciuser: ${{ env.ciuser }}
      TF_VAR_cipassword: ${{ env.cipassword }}
      TF_VAR_ssh_pub_key: ${{ env.ssh_pub_key }}
      TF_VAR_proxmox_api_token_id: ${{ env.proxmox_api_token_id }}
      TF_VAR_proxmox_api_token_secret: ${{ env.proxmox_api_token_secret }}
      TF_VAR_proxmox_api_url: ${{ env.proxmox_api_url }}
      TF_VAR_repo: ${{ env.repository }}
      TF_VAR_pat: ${{ env.pat }}
      TF_VAR_AWS_ACCESS_KEY_ID: ${{ env.minio_access_key }}
      TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ env.minio_secret_key }}
      Tf_VAR_AWS_ENDPOINT_URL_S3: ${{ env.minio_endpoint }}            


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Install 1Password CLI    
        uses: 1password/install-cli-action@v1

      - name: Configure 1Password CLI  
        uses: 1password/load-secrets-action/configure@v1
        with:
          #service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          connect-host: ${{ secrets.OP_CONNECT_HOST }}
          connect-token: ${{ secrets.OP_CONNECT_TOKEN }}

      - name: Load Terraform Credentials
        id: load-terraform-credentials
        uses: 1password/load-secrets-action@v1
        with:
            export-env: True
        env:
            ssh_password: op://secrets/Terraform/ssh_password
            ssh_user: op://secrets/Terraform/ssh_user
            ciuser: op://secrets/Terraform/ciuser
            cipassword: op://secrets/Terraform/cipassword
            ssh_pub_key: op://secrets/Terraform/ssh_pub_key
            proxmox_api_token_id: op://secrets/ProxmoxAPI/username
            proxmox_api_token_secret: op://secrets/ProxmoxAPI/password
            proxmox_api_url: op://secrets/Terraform/host
            minio_access_key: op://secrets/Terraform/minio_access_key
            minio_secret_key: op://secrets/Terraform/minio_secret_key
            minio_endpoint: op://secrets/Terraform/minio_endpoint
    
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
           node-version: '14'

      - name: 'Terragrunt Init'
        id: init
        run: terraform init
        
            
          
      - name: 'Terragrunt Plan'
        id: plan
        run: terraform plan       

      - name: 'Terragrunt Apply'
        id: apply
        run: terraform apply -auto-approve     
       

      

